baseURL = "/"
languageCode = "en-us"
title = "ASQ - Your Engineering Consultant"
theme = "forty"

DefaultContentLanguage = "en"

#staticDir = ["static1", "static2"]

[languages]
  [languages.en]
    contentDir = "content/en"
    title = "ASQ - Your Engineering Consultant"
  #  staticDir2 = "static"
    languageName = "English"
    weight = 1
  [languages.vi]
    contentDir = "content/vi"
    title = "Tư vấn ASQ"
    languageName = "Tiếng Việt"
  #  staticDir = ["staticDir_override", "static_vi"]
    weight = 2

    [languages.jp]
      contentDir = "content/jp"
      title = "ASQコンサルティング"
      languageName = "日本語"
    #  staticDir = ["staticDir_override", "static_vi"]
      weight = 3


defaultContentLanguageInSubdir = true



# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-20712415-4"

# Enter your disqus shortname to enable comments
disqusShortname = ""


###English Content

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "ASQ - Your Engineering Consultant"
  description = "ASQ is a spin-off start up Team originated from ETH Zurich and Kyoto University specialized in engineering asset management and data analytics and data solution for engineering systems"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "ASQ"
    subtitle = "Your Engineering Consultant"
    menu = "Menu"
    # Optional logo as brand stored in img/
#     logo = "/banner/logo.jpg"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

      [[params.navigation.links]]
        name = "News"
       url = "blogs/"


       [[params.navigation.links]]
         name = "Apps"
        url = "apps/"


       [[params.navigation.links]]
        name = "Our Expertise"
        url = "whatwedo"


#    [[params.navigation.links]]
#      name = "Projects"
  #    url = "projects"

#    [[params.navigation.links]]
#      name = "Meet Our Team"
    #  url = "blogs/ipsum"


#    [[params.navigation.links]]
#        name = "Publications"
  #      url = "elements.html"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Tiếng Việt"
      url = "/vi"


    [[params.navigation.button1]]
      name = "日本語"
      url = "/jp/about/Q-brochure-Nihongo.pdf"

    # Button Style 2
    # [[params.navigation.button2]]
    #   name = "Log In"
    #   url = "#"


  # Banner section
  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "ASQ Engineering and Research Hub"
    subtitle = "Due Diligence, Asset Management, Data Analytics, and Market Analysis for Engineering Systems"
    buttonText = "Get Started"
    image = "/banner/banner.jpg"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.

    [[params.tiles.showcase]]
      title = "Who We Are"
      subtitle = "A spin-off start up Team originated from ETH Zurich (Swizerland) and Kyoto University (Japan). We solve real world problems with practical experiences and state-of-the-art innovations in engineering and science"
      image = "/banner/pic01.jpg"
      url = "about/"

    [[params.tiles.showcase]]
      title = "Technical Due Diligence"
      subtitle = "We conduct Due Diligence studies on building systems, Infrastructure systems, and industrial sites using innovative digital tools and by experienced engineers to help Capital Investors arriving at optimal Merging and Acquisition decisions"
      image = "/banner/pic02.jpg"
      url = "whatwedo/tdd"

    [[params.tiles.showcase]]
      title = "Asset Management"
      subtitle = "We assist organizations to develop long term asset management blueprints and programs for sustainable growth. We build models to determine optimal preventive intervention strategies on assets using reliability based approach"
      image = "/banner/pic03.jpg"
      url = "whatwedo/am"

    [[params.tiles.showcase]]
      title = "Data Analytics and Modelling"
      subtitle = "We detect trends and identify bottlenecks of engineering systems using data science and advise Clients on effective solutions"
      image = "/banner/pic04.jpg"
      url = "whatwedo/datascience"

    # [[params.tiles.showcase]]
    #   title = "Construction Marketing"
    #   subtitle = "Conducting market research in construction sector and help Clients to select optimal sites or materials using supply and demand analysis"
    #   image = "/banner/pic05.jpg"
    #   url = "blogs/ipsum"

    [[params.tiles.showcase]]
      title = "Research & Education "
      subtitle = "In close collaboration with ETH Zurich, Kyoto University, and local universities, we are contributing to training & education for a next generation of reliability engineers in the region"
      image = "/banner/pic06.jpg"
      url = "whatwedo/training"

    [[params.tiles.showcase]]
      title = "Brochure "
      subtitle = "Download ASQ's Brochure in PDF format"
      image = "/banner/collaboration.png"
      url = "about/ASQ-brochure-English.pdf"
    # You can make more showcases by copy and pasting the code above
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "Our Blog"
    subtitle = """A collection of ASQ's news and articles"""
    buttonText = "Get Started"
    url = "blogs"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
     formEmail = "hallo.asq@protonmail.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "hallo.asq@protonmail.com"

    [[params.contact.phone]]
    title = "Phone"
    phone = "+84 98378 0100"

    [[params.contact.address]]
    title = "Address"
    street = "2001B C1 Tower, Rung Co, Ecopark"
    city = "Hung Yen"
    country = "Vietnam"

  # Footer section
  [params.footer]
    enable = true
    copyright = "ASQ - Your Engineering Consultant"




    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com"
      label = "LinkedIn"

    # [[params.footer.quicklinks]]
    #   text = "Design: "
    #   url= "https://www.html5up.net"
    #   alt = "HTML5 UP"



      ###Vietnamses Content

      [languages.vi.params]
        # You can use Markdown syntax for urls [text](//url.to/source)
        # To create multi-line text in strings use the """example Text""" format
        #
        # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
        # for more icons. The icons are represented by their corresponding
        # CSS class.

        # Provide your metadata here.
        name = "Your name"
        description = "Your description"

        # Link custom assets relative to /static
        custom_css = []
        custom_js  = []
        favicon    = "favicon.ico"

        # Just a custom image variable, please define it in .md files for content.
        image = ""

        # 404 error customization
        [languages.vi.params.error404]
          heading = "Page couldn't be found"
          text = "Please visit [this page](/)"

        # Navigation Section
        [languages.vi.params.navigation]
          title = "ASQ"
          subtitle = "Your Engineering Consultant"
          menu = "Trang Chủ"
          # Optional logo as brand stored in img/
          # logo = "/banner/logo.jpg"

          [[languages.vi.params.navigation.links]]
            name = "Tin Tức"
            url = "vi/blogs"

            [[languages.vi.params.navigation.links]]
              name = "Apps"
             url = "apps/"
          [[languages.vi.params.navigation.links]]
              name = "Dịch Vụ"
              url = "vi/whatwedo"


  #        [[languages.vi.params.navigation.links]]
  #          name = "Dự Án"
      #      url = "projects"

  #        [[languages.vi.params.navigation.links]]
  #            name = "Đội Ngũ Tư Vấn"
  #            url = "/vi"
  #            url = "elements.html"


  #        [[languages.vi.params.navigation.links]]
  #          name = "Thư Viện"
  #          url = "/vi"
      #      url = "elements.html"

          # Add custom links here by uncommenting code below. To remove links just delete
          # the [[params.navigation.links]] map associated with that link. Copy and paste
          # code below if you need more links. Buttons work in the same way.
          # [[params.navigation.links]]
          #    name = "NameOfLink"
          #    url = "UrlOfLink"

          # Button Style 1
          [[languages.vi.params.navigation.button1]]
            name = "English"
            url = "/"

          [[languages.vi.params.navigation.button1]]
            name = "日本語"
            url = "/jp/about/ASQ-brochure-Nihongo.pdf"
          # Button Style 2
  #        [[languages.vi.params.navigation.button2]]
  #          name = "Log In"
  #          url = "#"


        # Banner section
        [languages.vi.params.banner]
          # To change the background image on the homepage banner, replace 'banner.jpg' in
          # the 'static/img' folder.
          title = "Tư Vấn ASQ"
          subtitle = "Cung cấp dịch vụ tư vấn kĩ thuật chuyên nghiệp trong lĩnh vực đánh giá và quản lý tài sản cơ sở hạ tầng và các hệ thống kĩ thuật, lập các mô hình toán tối ưu dựa trên dữ liệu vận hành và bảo trì, đánh giá và phân tích thị trường xây dựng."
          buttonText = "Tìm hiểu thêm"


        # Tiles Section
        [languages.vi.params.tiles]
          enable = true
          # Display your showcases here.

          [[languages.vi.params.tiles.showcase]]
            title = "Giới thiệu"
            subtitle = "ASQ được thành lập như là một sản phẩm Spin-off từ các công trình nghiên cứu tại viện công nghệ thụy Sĩ ETH và đại học Kyoto Nhật Bản. ASQ có thế mạnh trong lĩnh vực áp dụng các mô hình toán xác xuất thống kê và toán ứng dụng trong lĩnh vực xây dựng và quản lý thiết bị và tài sản hạ tầng"
            image = "/banner/pic01.jpg"
            url = "vi/about/"
            # url = "blogs/aliquam"


          [[languages.vi.params.tiles.showcase]]
            title = "Đánh giá các hệ thống kĩ thuật công trình"
            subtitle = "ASQ giúp chủ đầu tư đưa ra được các quyết định chiến lược trong việc mua và sát nhập qua việc khảo sát và đánh giá và thẩm tra các hệ thống kĩ thuật như tòa nhà, công trình công nghiệp và nhà máy"
            url = "vi/whatwedo/tdd"

            image = "/banner/pic02.jpg"
            # url = "blogs/aliquam"

          [[languages.vi.params.tiles.showcase]]
            title = "Quản lý tài sản công trình và thiết bị"
            subtitle = "ASQ giúp doanh nghiệp và các tổ chức quản lý tốt tài sản thông qua việc phát triển các kế hoạch chiến lược và xây dựng các mô hình toán tối ưu để đưa ra các biện pháp bảo hành và bảo trì hợp lý và tối ưu"
            url = "whatwedo/am"
            image = "/banner/pic03.jpg"
            # url = "blogs/tempus"

          [[languages.vi.params.tiles.showcase]]
            title = "Phân tích và xử lý dữ liệu"
            subtitle = "Sử dụng các mô hình thống kê và cơ sở dữ liệu lớn để dự báo xu hướng và phát hiện ra các vấn đề của hệ thống, từ đó đưa ra cảnh báo sớm và các phương pháp xử lý tối ưu"
            image = "/banner/pic04.jpg"
            url = "whatwedo/datascience"
            # url = "blogs/magna"

          # [[languages.vi.params.tiles.showcase]]
          #   title = "Nghiên cứu thị trường trong ngành xây dựng"
          #   subtitle = "Chúng"
          #   image = "/banner/pic04.jpg"
          #   url = "blogs/ipsum"

          # [[languages.vi.params.tiles.showcase]]
          #   title = "Dịch vụ BPO"
          #   subtitle = "Ipsum Dolor Sit Amet"
          #   image = "/banner/pic05.jpg"
          #   url = "blogs/ipsum"

          [[languages.vi.params.tiles.showcase]]
            title = "Nghiên cứu và Giáo Dục"
            subtitle = "Phối hợp và cộng tác với  nhóm nghiên cứu của học viện ETH, Zurich, Thụy Sĩ và đại học Kyoto trong công tác nghiên cứu và giảng dạy, trang bị cho các kĩ sư tương lai các kiến thức tính toán độ tin cậy, thống kê, vận trù học, và toán ứng dụng tối ưu hệ thống"
            image = "/banner/pic06.jpg"
            url = "whatwedo/training"
            # url = "blogs/ipsum"
          # You can make more showcases by copy and pasting the code above


          [[languages.vi.params.tiles.showcase]]
            title = "Hồ sơ giới thiệu ASQ bản PDF"
            subtitle = "Tải hồ sơ ASQ để biết thêm về năng lực, đề tài nghiên cứu, và các sản phẩm dịch vụ"
            image = "/banner/collaboration.png"
            url = "about/ASQbrochure-en.pdf"


        [languages.vi.params.blog]
          # All blogs defined in their own files. You can find example blogs
          # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
          # at the root of this Hugo site.
          # For more informtion take a look at the README.
          # To add more blogs just copy and paste the code.

        # Section Type Two
        [languages.vi.params.two]
          enable = true
          title = "Tin tức"
          subtitle = """Thông tin về dự án và các bài viết chuyên môn """
          buttonText = "Tìm hiểu thêm"
          url = "vi/blogs"


        # Contact section
        [languages.vi.params.contact]
          enable = true
          buttonSend = "Gửi tin"
          buttonClear = "Xóa"

          # Since this template is static, the contact form uses www.formspree.io as a
          # proxy. The form makes a POST request to their servers to send the actual
          # email. Visitors can send up to a 1000 emails each month for free.
          #
          # What you need to do for the setup?
          #
          # - set your email address under 'email' below and uncomment
          # - upload the generated site to your server
          # - send a dummy email yourself to confirm your account
          # - click the confirm link in the email from www.formspree.io
          # - you're done. Happy mailing!
          # formEmail = "example@domain.com"

          # Contact Section
          # You can add multiple emails, phone numbers, or addresses
          # by copying the corresponding map with frontmatter code.
          [[languages.vi.params.contact.email]]
          title = "Thư điện tử"
          email = "hallo.asq@protonmail.com"

          [[languages.vi.params.contact.phone]]
          title = "Điện thoại"
          phone = "+84983780100"

          [[languages.vi.params.contact.address]]
          title = "Địa chỉ"
          street = "Phòng 2001B Tòa nhà C1, Rừng Cọ, Ecopark"
          city = "Văn Giang, Hưng Yên"
          country = "Việt Nam"

        # Footer section
        [languages.vi.params.footer]
          enable = true
          copyright = "Tư vấn ASQ"

          # Uses font awesome icons

          [[languages.vi.params.footer.social]]
            icon = "fa-github"
            url= "https://www.github.com"
            label = "GitHub"

          [[languages.vi.params.footer.social]]
            icon = "fa-linkedin"
            url= "https://www.linkedin.com"
            label = "LinkedIn"

          # [[languages.vi.params.footer.quicklinks]]
          #   text = "Design: "
          #   url= "https://www.html5up.net"
          #   alt = "Hi"
